# Setup
title:               Projeto - Visualização de Dados
tagline:             ''
description:         Página para o projeto final da disciplina de Visualização de Dados
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Felipe Ribeiro e Gustavo Lelis

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
